Resolved code quality issues
ERROR: [ANSIBLE0007] Standard 'Name of tasks and handlers must be formatted' not met:
... tasks/check_variables.yml:4: name 'check nutanix_prism_eula_host' should start with uppercase

ERROR: [ANSIBLE0007] Standard 'Name of tasks and handlers must be formatted' not met:
... tasks/check_variables.yml:10: name 'check nutanix_prism_eula_password' should start with uppercase

ERROR: [ANSIBLE0001] Standard 'Single tasks should be separated by empty line' not met:
... tasks/eula.yml:1: missing task separation (required: 1 empty line)

ERROR: [LINT0004] Standard 'YAML should contain document start marker' not met:
... tasks/eula.yml:1: missing document start "---"

ERROR: [ANSIBLE0006] Standard 'Tasks and handlers must be named' not met:
... tasks/check_variables.yml:16: module 'ansible.builtin.fail' used without or empty `name` attribute

ERROR: [LINT0002] Standard 'YAML should not contain unnecessarily empty lines' not met:
... tasks/eula.yml:1: missing document start "---"